# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - 'master'
    paths:
      - 'mkdocs/**'
      - '.github/workflows/**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:9.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build mkdocs
        run: |
          mkdocs build --strict --verbose -f mkdocs/config/ru/mkdocs.yml
          mkdocs build --strict --verbose -f mkdocs/config/en/mkdocs.yml
          mkdir public
          mv mkdocs/generated/ru public/ru
          mv mkdocs/generated/en public/en
          mv mkdocs/index.html public
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs
          path: './public'

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdocs
          path: './public'
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
